### PR TITLE
add allowed commands whitelist, and move full bypass check to permission

### PR DESCRIPTION
**Pull request by 456dev**
done by adding a config option for world.parkour-allowed-commands, matching on prefix instead of base, so /parkour home can be allowed without anything else

im not sure if there is a more correct way to check permissions, so welcoming reviews / changes

### CODE REVIEW

**Review by tastybento — APPROVED** [review]
Looks good to me, thanks!

**Comment by tastybento** [comment]
I have thought that maybe there should be a `/pk quit` command to quit a course that is mid-run. Sometimes you just cannot do something.

**Comment by 456dev** [comment]
agree, an alternative to relogging would be good. do you want me to try and add this in this pr?

**Comment by 456dev** [comment]
hmm the check failed, but i dont think its my fault (this time)

**Comment by tastybento** [comment]
Do a different PR for the quit command. I'm going to merge this and then double check the static analysis setup.

**Pull request merged**
